### ISSUE TITLE
Better idea for a file extension name.

### ISSUE THREAD

**Issue by WilliamDue** [diku-dk/alpacc#15]
Currently grammars use `.cg` as a file extension. Maybe it should be something like `.alp` or maybe the format should be changed and it should just piggy back ride of Lex and Yacc?

**Comment by athas** [comment]
`.alp` is good.

**Comment by WilliamDue** [comment]
Changed in https://github.com/diku-dk/alpacc/commit/3d3b4dede4ccf2d5983634f620d7b17b43aa91bb
