### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by athas** [diku-dk/alpacc#2]
`parallel-parser` is a terrible name for a program, and will not suffice if (once!) this actually becomes useful.  Even something like `llpgen` would be better, but a more poetic name would be ideal.

**Comment by joshniemela** [comment]
I suggest some nordic deity like Heimdall, Mimir, Brokkr, Loki, etc

**Comment by athas** [comment]
Who is the Asgardian god of context-free languages?

**Comment by athas** [comment]
The classic parser generator is named `yacc`.  A Danish equivalent would be `moskus`, or maybe `hjort` or `rensdyr`.  The latter two have the nice property of being difficult to pronounce.

**Comment by WilliamDue** [comment]
I like `moskus` because it looks and sounds nice. But I also think if it is an animal it should be a more speedy ungulate? I have looked around but I can not find animals with as good names.

**Comment by athas** [comment]
Deer are pretty fast and they live in herds, which is a bit like parallelism if you squint a lot.

**Comment by nqpz** [comment]
What about `ulv`? Wolfes eat bison, which in my view puts them higher in the hierarchy of mammals.

**Comment by WilliamDue** [comment]
How about something like `alpacc` (A Lovely Parallelly Accelerated Compiler Compiler) I think the acronym might be a bit Volapük but it is a fun reference to yacc.

**Comment by athas** [comment]
`alpacc` is good, but there is no reason to use so many adverbs: A Lovely Parallel Accelerated Compiler Compiler.

**Comment by athas** [comment]
Or "Array Language Parallelism-Accelerated Compiler Compiler".  Many speculative expansions are possible!

**Comment by WilliamDue** [comment]
That's a better acronym, the lovely part is really out of nowhere.

**Comment by athas** [comment]
Alright, then rename it.

**Comment by WilliamDue** [comment]
I think I do not have permissions to do it, I can not see any settings.

**Comment by athas** [comment]
Rename the program itself. I will handle the repository.
